### PR TITLE
#79 Introduce refresh token mechanism

### PR DESCRIPTION
**Pull request by xxi511**
integrate refresh token mechanism into launch flow in ApplicationCoordinator.swift

### CODE REVIEW

**Comment by denkeni** [comment]
This implementation calls API `/account/refresh` at every app launch, resulting in unnecessary calls.

Wouldn’t it be more efficient to validate the `access_token` before refreshing?

**Comment by xxi511** [comment]
Ummm. API response doesn’t provide expired date 
there are 2 possible solutions
1. We know the expired date is 1 day so we can add the date field for access token and refresh token by ourself 
2. Integrate jwt library to parse the access token to get expired date, not ideal to me, I don’t think this is not client should do

**Comment by denkeni** [comment]
That’s a great suggestion for the API spec to add an expiration date for tokens. I’ll have @chhsiao1981 for further discussions.

**Comment by chhsiao1981** [comment]
ok～
I'll add expiration date when returning the tokens.

**Comment by xxi511** [comment]
Update PR to use expired date.

**Comment by chhsiao1981** [comment]
> Update PR to use expired date.
> 
> I think there is a potential issue For example, the access token will expire in 10 mins when user launch the app we don't refresh token. 10 mins later, token expire and there is no refresh token mechanism. Will fix this issue in another PR.

The expire-time of the refresh token (7 days) is larger than the expire-time of the access-token (1 day).

**Comment by xxi511** [comment]
I mean app should be able to refresh token during calling API, not only refresh when app launch

**Comment by xxi511** [comment]
Close, please review https://github.com/Ptt-official-app/Ptt-iOS/pull/85

**Pull request closed without merging**
