### PR TITLE
keychain improve

### PR DESCRIPTION
**Pull request by xxi511**
* Rename to `KeyChainItem`.  
* Improve key chain to save/ read text, data and coddle 
* Add `user_id` to `APIModel.LoginToken` 
* Update related keychain usage.  

Note this PR is not back compatible     
User need to login again after this MR.  

Some API need `user_id` which is new to iOS app.   
I think user have to login again so we can have this value, right?

### CODE REVIEW

**Comment by denkeni** [comment]
> Some API need user_id which is new to iOS app.
> I think user have to login again so we can have this value, right?

No. There's an API for that: [/api/userid](https://api.devptt.dev:5000/#/user/get_api_userid)
It works, with Bearer authentication.

> Note this PR is not back compatible
> User need to login again after this MR.

I saw that you replaced `kSecAttrService` with `kSecAttrAccount`, but it only accepted `enum Key` and just for introducing `.unitTest`. Wouldn't it be great to make it allow multiple accounts?

**Comment by xxi511** [comment]
If there is `/api/userid`     
I can add a function to get userID in `APIClient`.    
Something like this, what do you think
```
        if let id = KeyChainItem.readText(for: .userID) {
            completion(id)
        } else {
            // call api
        }
```

The purpose of `enum Key` is to help dev to understand what kind of data is saved in key chain  
So far it only contains `loginToken` and `unitTest` but we can add more if needed.  
For example, to keep back compatible, we might want to save `bear token` and `userID` independently    
Maybe we want to save login credentials as well       

I could be wrong but from my understanding, it is just a filed name doesn't mean a real "account".   
You can use the field to query, It is the same to use `kSecAttrLabel`.       
It is totally fine to use `kSecAttrService` if we want to keep back compatible

**Comment by denkeni** [comment]
That would make getting `userID` as an asynchronous function, right? I'm not sure that would be a good interface, so I'm open to hear from others.

Rather than being in `APIClient`, it could make more sense to be in `User` model (not exists yet)? So `APIClient` would always guarantee retrieving the latest info from backend, without side effect.

And yeah, I would guess Keychain item attribute keys are just for ready use. Since we're in closed beta testing, back incompatibility could be acceptable. It simply came to my mind that it would be more meaningful to bring new feature while breaking change 😉.

**Comment by scsonic** [comment]
I remeber the login api has no user_id before,
today, the login api has user_id
https://api.devptt.dev:5000/#/user/post_api_account_login
{
  "user_id": "string",
  "access_token": "string",
  "token_type": "string"
}
We can use the the field and don't make a async api again

**Comment by xxi511** [comment]
> That would make getting userID as an asynchronous function,

Exactly, it has to be async function     
If async is acceptable, 9c79f8304b255cbc953629c1631340104dc35be0 this is back compatible (I revert the change)     
If not, I am afraid user needs to login again.

**Pull request merged**
